name: fragalysis_env
channels:
  - rdkit
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - biopython=1.74=py37h7b6447c_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.10.16=0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.9.11=py37_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - jpeg=9b=h024ee3a_2
  - libboost=1.67.0=h46d08c1_4
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1d=h7b6447c_3
  - pandas=0.25.2=py37he6710b0_0
  - pcre=8.43=he6710b0_0
  - pillow=6.2.0=py37h34e0f95_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h7b6447c_0
  - py-boost=1.67.0=py37h04863e7_4
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.0=py37_0
  - pytz=2019.3=py_0
  - rdkit=2019.09.1.0=py37hc20afe1_1
  - readline=7.0=h7b6447c_5
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/sabs-r3/anaconda3/envs/fragalysis_env

